remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Chris Swart
description: Some basic examples of client interfaces to a computer vision API based on Jeremy Howard's tinypets https://github.com/fastai/tinypets

author:
  name: Chris Swart
